Add subscription hooks to Mercurius
mercurius-js/mercurius pull request #407
Opened 2021-02-24 07:57 UTC by jonnydgreen

Closes: https://github.com/mercurius-js/mercurius/issues/406

2021-02-24 08:20 UTC, mcollina reviewed
Good work! Why did you add all the nextTick?

2021-02-24 08:26 UTC, jonnydgreen commented
Thanks! For `nextTick`, I followed the Node.js docs examples that used `once` as I wanted to guarantee that I was listening with `once` before the event was fired: https://nodejs.org/api/events.html#events_events_once_emitter_name_options

2021-02-24 08:45 UTC, mcollina requested changes
I think you can safely remove most (if not all) `nextTick`. When you write to a socket the messages go through a few full event loop cycles.

2021-02-24 08:45 UTC, mcollina commented on test/subscription-hooks.js
> +  })
there is no need for this `nextTick`.

2021-02-24 08:45 UTC, mcollina commented on test/subscription-hooks.js
> +  })
there is no need for this nextTick

2021-02-24 09:01 UTC, jonnydgreen commented
Makes sense - I'll get on that now!

2021-02-24 09:22 UTC, mcollina requested changes

2021-02-24 09:22 UTC, mcollina commented on lib/subscription-connection.js
> +          this.handleConnectionClose()
I think we should return after calling this function.

2021-02-24 09:34 UTC, mcollina approved these changes
lgtm

2021-02-24 10:11 UTC, PacoDu reviewed
lgtm ! Maybe we could also add a hook when the subscription ends ? (when `GQL_STOP` is received)

2021-02-24 10:14 UTC, jonnydgreen commented
For sure - I'll add that later along with the updated lifecycle! :)

2021-02-24 23:36 UTC, PacoDu approved these changes
lgtm !

2021-02-25 00:54 UTC, mcollina approved these changes
lgtm

2021-02-25 00:54 UTC, merged