fix: improve error messaging for gateway
mercurius-js/mercurius pull request #425
Opened 2021-03-16 23:08 UTC by jkirkpatrick24

# Summary

Adds some additional error messaging for gateways that are configured to consume remote services. Previously, if a gateway loaded a remote service and that service had an invalid schema, the gateway would attempt to build a federated schema  and the result of that is a GQL parsing error: `Syntax Error: Unexpected <EOF>.`. 

This pull request adds an additional check before attempting to build the federated schema. If there are no valid SDLs that have been provided to the gateway, we inform the user that this is the case. 

I also added a couple of tests that check the error handling behaviour of a gateway that is consuming remote services.

# Caveats

This is probably more useful for development, but I though this messaging might help other developers locate similar issues faster than it took me!

2021-03-17 08:54 UTC, mcollina requested changes
Good work!

2021-03-17 08:54 UTC, mcollina commented on test/gateway/remote-services.js
> +const { test } = require('tap')
add use strict at the top

2021-03-17 08:54 UTC, mcollina commented on lib/gateway.js
> +    .filter(schemaDefinition => schemaDefinition !== '')
I would use fastify.log.warn.

2021-03-17 20:29 UTC, jkirkpatrick24 commented on test/gateway/remote-services.js
> +const { test } = require('tap')
👍

2021-03-17 20:33 UTC, jkirkpatrick24 commented
@PabloSzx and @mcollina thank you for the review! I've updated to add the warning when a service fails to initialize. Is that in line with what you were thinking?

2021-03-18 14:37 UTC, PabloSzx requested changes
After that minor test improvement, everything looks good, thanks 👍

2021-03-18 14:37 UTC, PabloSzx commented on test/gateway/remote-services.js
> +  const gateway = Fastify()
```suggestion
  const gateway = Fastify({
    logger: true
  })

  let warnCalled = 0;
  gateway.log.warn = (message) => {
    warnCalled++;
    t.matchSnapshot(message)
  }

```

Testing that the warning is actually called

2021-03-18 14:37 UTC, PabloSzx commented on test/gateway/remote-services.js
> +  }
```suggestion
  }
  t.equal(warnCalled, 1, "Warning is called")
```

2021-03-18 16:42 UTC, mcollina approved these changes
lgtm

2021-03-19 02:10 UTC, jkirkpatrick24 commented
Thanks again @mcollina and @PabloSzx for the reviews. I've added the suggested changes. If theres anything else needed let me know 😄

2021-03-19 02:18 UTC, PabloSzx approved these changes
looks good 👍

2021-03-19 11:41 UTC, merged