Check for loader existence before calling it
mercurius-js/mercurius pull request #512
Opened 2021-06-12 21:35 UTC by kidqueb

https://github.com/mercurius-js/mercurius/issues/511

Made an interim PR to patch the error preventing the payload from sending over what it can incase this is at all helpful. Will follow up on that issue when I can get back to this in the upcoming week.

2021-06-12 22:43 UTC, mcollina requested changes
Can you please add a unit test?

2021-06-13 19:09 UTC, kidqueb reviewed
Modified to account for existing data instead of returning null and added a test 👍

Edit: Oops, commented as a review ha

2021-06-13 22:11 UTC, mcollina approved these changes
lgtm

2021-06-13 22:17 UTC, jonnydgreen approved these changes

2021-06-14 22:14 UTC, closed without merging