Add missing context for subscription loaders
mercurius-js/mercurius pull request #567
Opened 2021-09-13 03:56 UTC by ekosz

When developing I noticed that the second argument of my loaders was always `undefined` when being processed by a subscription.

Looks like the fix is just to pass it in when we init the subscription `kLoaders`. That said, maybe there is a good reason for this that I don't know about?

Happy to further iterate on this!

2021-09-13 07:03 UTC, mcollina requested changes
Can you please add a unit test?

2021-09-18 16:44 UTC, ekosz commented
@mcollina Sorry about that. I added a unit test and made sure it failed before my fix was applied. Please let me know what else I can do to help!

2021-09-18 17:10 UTC, mcollina approved these changes
lgtm

2021-09-18 17:16 UTC, mcollina commented
CI is failing.

2021-09-19 20:53 UTC, ekosz commented
@mcollina Again, really sorry about that. Pushed up the lint fixes

2021-09-20 10:22 UTC, mcollina approved these changes
lgtm

2021-09-20 10:22 UTC, merged