Fix #568
mercurius-js/mercurius pull request #570
Opened 2021-09-19 11:00 UTC by puchm

This is a draft.

I have tried using `GraphiQL.createFetcher` in order to create a fetcher that works properly for subscriptions.

However, the WebSocket is getting closed with code **1002** every time I try to open a subscription. This has already been reported in https://github.com/graphql/graphiql/issues/1800 but the issue is still the same after changing the GraphiQL version.

Any ideas?

2021-09-19 14:25 UTC, mcollina commented
I don't know why it fails :( Have you tried looking at the messages that are being sent back and forth?

What's the server are you testing against?

2021-09-21 08:20 UTC, puchm commented
@mcollina I am testing against a simple mercurius server.
<details>
<summary>Server implementation</summary>

```ts
const Fastify = require('fastify');
const mercurius = require('./mercurius');

const app = Fastify();

const gql = String.raw

const schema = gql`
    type Query {
        me: String
    }

    type Subscription {
        commentAdded: Comment!
    }

    type Comment {
        text: String
    }

    type Mutation {
        addComment(text: String): Boolean!
    }
`

const resolvers = {
    Query: {
        me: () => 'Hello there.'
    },
    Mutation: {
        addComment: (_parent, { text }, { pubsub }) => {
            pubsub.publish({
                topic: 'COMMENT',
                payload: {
                    value: text
                }
            });

            return true;
        }
    },
    Subscription: {
        commentAdded: {
            subscribe: (_root, _args, { pubsub }) => pubsub.subscribe('COMMENT')
        }
    }
}

app.register(mercurius, {
    graphiql: true,
    resolvers: resolvers,
    schema: schema,
    subscription: {
        onConnect: () => {
            console.log("hiii")
        }
    }
})

app.listen(4001).then(() => console.log("HI there"))
```
</details>

I asked on the Apollo GraphQL discord and apparently this could be caused by the server using the legacy websockets protocol instead of `graphql-ws`.

2021-09-21 10:06 UTC, puchm commented
It is working now using the `legacyClient` option. Request headers and query variables are also working fine.

2021-09-21 10:32 UTC, mcollina requested changes

2021-09-21 10:32 UTC, mcollina commented
> It is working now using the `legacyClient` option. Request headers and query variables are also working fine.

Good spot!

2021-09-21 10:38 UTC, puchm commented
Good point, fixed that.

2021-09-21 12:44 UTC, mcollina commented on static/main.js
> +  const subscriptionUrl = `ws://${host}${window.GRAPHQL_ENDPOINT}`
You need to use `wss` when `window.location.protocol` is `https`.

2021-09-23 18:32 UTC, puchm commented
Should be fine now.

2021-09-24 07:54 UTC, mcollina approved these changes
lgtm

2021-09-24 07:54 UTC, merged